Table users {
	id bigint [ pk, increment, not null, unique ]
	name varchar [ not null ]
	email varchar [ not null, unique ]
	email_verified_at timestamp
	workos_id varchar [ not null, unique, note: 'ID do workOS' ]
	avatar text [ not null ]
	role char [ not null, default: 'c', note: 'Valores disponíveis "c" para clientes ou "a" para administradores.' ]
}

Table products {
	id integer [ pk, increment, not null, unique ]
	name varchar [ not null, unique ]
	price integer [ not null, note: 'Registrado em centavos para evitar problemas de float point.' ]
	cost_price integer [ note: 'Registrado em centavos para evitar problemas de float point.' ]
	stock integer [ note: 'Stock vai existir se o produto não tiver variação, quando tem a variação, o estoque é considerado de acordo com a variação selecionada.' ]
	thumbnail text [ not null ]
	images text [ not null, note: 'Armazena um array de imagens de produtos' ]
	short_description varchar [ not null ]
	description text
	rating smallint [ not null, default: 0, note: 'Avaliação de 0 a 5' ]
	SKU varchar
	updated_at timestamp
	created_at timestamp [ not null ]

	indexes {
		(name) [ name: 'products_index_0' ]
	}
}

Table product_attributes {
	id integer [ pk, increment, not null, unique ]
	product_id integer [ not null ]
	attribute_id integer [ not null ]

	Note: 'Vinculo entre atributos e produtos'
}

Table attributes {
	id integer [ pk, increment, not null, unique ]
	name varchar [ not null ]
	product_ids integer
}

Table variation_attributes {
	id integer [ pk, increment, not null, unique ]
	variation_id integer [ not null ]
	attribute_id integer [ not null ]

	Note: 'Tabela de relação entre um atributo e uma variação'
}

Table variations {
	id integer [ pk, increment, not null, unique ]
	name varchar [ not null ]
	image_url text
	price integer
	stock integer
	sku varchar
	available smallint [ not null, default: 0, note: 'O campo de disponibilidade é usado para produtos virtuais.' ]
}

Table orders {
	id bigint [ pk, increment, not null, unique ]
	user_id bigint [ not null ]
	created_at timestamp [ not null ]
	status varchar [ not null, default: 'pending', note: '`pending`, `processing`, `shipped` , `delivered`, `cancelled`, `refunded`, `failed`, `on_hold`, 
`completed`' ]
	payment_method varchar [ not null ]
}

Table order_items {
	id bigint [ pk, increment, not null, unique ]
	order_id bigint [ not null ]
	product_id integer [ not null ]
	variation_id integer [ not null ]
	quantity integer [ not null ]
	unit_price integer [ not null ]
}

Table customer_cards {
	id integer [ pk, increment, not null, unique ]
	user_id bigint [ not null ]
	card_token varchar [ not null ]
	card_last4 char [ not null ]
	card_brand varchar [ not null ]
	created_at timestamp [ not null ]
}

Ref fk_product_attributes_product_id_products {
	product_attributes.product_id - products.id [ delete: no action, update: no action ]
}

Ref fk_product_attributes_attribute_id_attributes {
	product_attributes.attribute_id - attributes.id [ delete: no action, update: no action ]
}

Ref fk_variation_attributes_attribute_id_attributes {
	variation_attributes.attribute_id - attributes.id [ delete: no action, update: no action ]
}

Ref fk_variation_attributes_variation_id_variations {
	variation_attributes.variation_id - variations.id [ delete: no action, update: no action ]
}

Ref fk_orders_user_id_users {
	orders.user_id - users.id [ delete: no action, update: no action ]
}

Ref fk_order_items_order_id_orders {
	order_items.order_id - orders.id [ delete: no action, update: no action ]
}

Ref fk_order_items_product_id_products {
	order_items.product_id - products.id [ delete: no action, update: no action ]
}

Ref fk_order_items_variation_id_variations {
	order_items.variation_id - variations.id [ delete: no action, update: no action ]
}

Ref fk_customer_cards_user_id_users {
	customer_cards.user_id - users.id [ delete: no action, update: no action ]
}